version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: leave_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: leave_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leave.rule=Host(`leave.localhost`)"
      - "traefik.http.routers.leave.entrypoints=websecure"
      - "traefik.http.routers.leave.tls=true"
      - "traefik.http.services.leave.loadbalancer.server.port=80"
    networks:
      - traefik_network

  db:
    image: mysql:8.0
    container_name: leave_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  traefik:
    image: traefik:v2.10
    container_name: leave_traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./ssl:/ssl
    networks:
      - traefik_network

volumes:
  dbdata:

networks:
  traefik_network:
    driver: bridge
