services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: leave_app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: leave_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: leave_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
